GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJJd2FuIFNhZnJ1ZGluIiwiZW1haWwiOiJpd2Fuc2FmckBnbWFpbC5jb20iLCJpYXQiOjE2NjgwNTQxODcsImV4cCI6MTY2ODA1NDIwN30.m_x7qnHMqQgZ2tf0PCJIXwwUbvY1IwrjhdbYuifG1wM

###

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Iwan Safrudin",
    "email": "iwansafr@gmail.com",
    "password":"123456",
    "confPassword":"123456"

}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "iwansafr@gmail.com",
    "password":"123456"
}

###
GET http://localhost:3000/token HTTP/1.1

###
DELETE http://localhost:3000/logout